naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
  MatchingDeclarationName:
    active: false
  InvalidPackageDeclaration:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
